apiVersion: v1
kind: Service
metada:
  labels:
    app: hello-app
  name: hello-app-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  selector:
    app: hello-app
  type: NodePort

